"""Docker-based Hermes test environment for plugin integration testing.

Provides :class:`HermesDockerTestEnv` — a context manager that provisions
a clean Hermes environment inside Docker, installs a plugin, and allows
running CLI commands against it. Designed for CI and local development.

Usage::

    from fabricium.testing import HermesDockerTestEnv

    env = HermesDockerTestEnv(
        plugin_name="caelterra",
        plugin_dir=Path(__file__).parent.parent,
    )
    with env:
        result = env.run_cli("caelterra", "setup")
        assert result.exit_code == 0
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Public types
# ---------------------------------------------------------------------------


@dataclass
class CliResult:
    """Result of a ``hermes <args>`` invocation inside the container."""

    exit_code: int
    stdout: str
    stderr: str

    @property
    def success(self) -> bool:
        return self.exit_code == 0

    def contains(self, text: str) -> bool:
        """Return True if *text* appears in stdout."""
        return text in self.stdout


@dataclass
class HermesConfig:
    """Configuration for the test Hermes environment.

    Reads provider / API key from environment variables (or a ``.env`` file).
    """

    provider: str = ""
    model: str = ""
    api_key: str = ""

    #: Additional environment variables to forward into the container.
    extra_env: dict[str, str] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.provider:
            self.provider = os.environ.get("FABRICIUM_TEST_PROVIDER", "deepseek")
        if not self.model:
            self.model = os.environ.get("FABRICIUM_TEST_MODEL", "deepseek/deepseek-chat")
        if not self.api_key:
            # Try provider-specific env var first, then generic fallback
            provider_upper = self.provider.upper()
            self.api_key = os.environ.get(
                "FABRICIUM_TEST_API_KEY",
                os.environ.get(f"{provider_upper}_API_KEY", ""),
            )

    @property
    def is_configured(self) -> bool:
        """Return True when enough config is present to run Hermes."""
        return bool(self.provider and self.model and self.api_key)


# ---------------------------------------------------------------------------
# Docker test environment
# ---------------------------------------------------------------------------

DOCKER_IMAGE = "nousresearch/hermes-agent:latest"

# Files that must exist for Hermes to recognise a plugin directory.
PLUGIN_YAML_TEMPLATE = """\
name: {name}
version: "1.0.0"
description: "Test plugin — auto-generated by fabricium test harness."
"""

CONFIG_YAML_TEMPLATE = """\
# Auto-generated by fabricium test harness
model:
  default: "{model}"
  provider: "{provider}"
"""


class HermesDockerTestEnv:
    """Provision a throw-away Hermes environment in Docker for CLI testing.

    Parameters
    ----------
    plugin_name:
        The plugin's CLI namespace (e.g. ``"caelterra"``).
    plugin_dir:
        Path to the plugin's source directory.  Must contain ``plugin.yaml``
        (or ``__init__.py`` with a ``register(ctx)`` function) so Hermes can
        discover it.
    fabricium_src:
        Path to the fabricium source tree.  Mounted into the container so
        the plugin can ``import fabricium``.  When ``None``, fabricium must
        already be installed inside the Docker image.
    config:
        Hermes provider / model configuration.  Reads from env vars by default.
    image:
        Docker image to use.  Defaults to the official Hermes Agent image.
    keep:
        If ``True``, do NOT tear down the container / temp directory on exit.
        Useful for debugging failing tests.
    """

    def __init__(
        self,
        plugin_name: str,
        plugin_dir: Path,
        fabricium_src: Path | None = None,
        config: HermesConfig | None = None,
        image: str = DOCKER_IMAGE,
        keep: bool = False,
    ) -> None:
        self.plugin_name = plugin_name
        self.plugin_dir = Path(plugin_dir).resolve()
        self.fabricium_src = Path(fabricium_src).resolve() if fabricium_src else None
        self.config = config or HermesConfig()
        self.image = image
        self.keep = keep

        # Private state — populated in start()
        self._temp_dir: Path | None = None
        self._container_name: str = ""
        self._started = False

    # ── Context manager ─────────────────────────────────────────────

    def __enter__(self) -> "HermesDockerTestEnv":
        self.start()
        return self

    def __exit__(self, *args: Any) -> None:
        self.stop()

    # ── Lifecycle ───────────────────────────────────────────────────

    def start(self, *, skip_fabricium_install: bool = False) -> None:
        """Pull image (if needed), create temp dir, launch container, install plugin.

        Parameters
        ----------
        skip_fabricium_install:
            If ``True``, skip the ``uv pip install fabricium`` step.  Use
            when the plugin vendors fabricium or doesn't depend on it.
        """
        if self._started:
            return

        self._ensure_image()

        self._temp_dir = Path(tempfile.mkdtemp(prefix="fabricium-test-"))
        self._container_name = f"fabricium-test-{self.plugin_name}-{os.getpid()}"

        self._write_hermes_home()
        self._install_plugin()
        self._start_container()
        self._install_fabricium(skip=skip_fabricium_install)
        self._wait_ready()
        self._enable_plugin()

        self._started = True

    def stop(self) -> None:
        """Stop and remove the container, then delete the temp directory."""
        if self._container_name:
            subprocess.run(
                ["docker", "rm", "-f", self._container_name],
                capture_output=True,
                timeout=30,
            )
        if self._temp_dir and self._temp_dir.exists() and not self.keep:
            shutil.rmtree(self._temp_dir, ignore_errors=True)
        self._started = False

    # ── CLI execution ───────────────────────────────────────────────

    def run_cli(self, *args: str, timeout: int = 60) -> CliResult:
        """Execute ``hermes <args>`` inside the container and return the result.

        Parameters
        ----------
        *args:
            Positional arguments passed to ``hermes`` (e.g. ``"my-plugin"``,
            ``"status"``).
        timeout:
            Maximum seconds to wait for the command to finish.
        """
        if not self._started:
            raise RuntimeError("Container not started — call start() first.")

        cmd = ["docker", "exec", self._container_name, "hermes", *args]
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return CliResult(
            exit_code=proc.returncode,
            stdout=proc.stdout,
            stderr=proc.stderr,
        )

    def run_cli_json(self, *args: str, timeout: int = 60) -> dict[str, Any]:
        """Like :meth:`run_cli` but parse stdout as JSON."""
        result = self.run_cli(*args, timeout=timeout)
        try:
            return json.loads(result.stdout)  # type: ignore[no-any-return]
        except json.JSONDecodeError:
            return {"_raw": result.stdout, "_parse_error": True}

    # ── Internal helpers ────────────────────────────────────────────

    def _ensure_image(self) -> None:
        """Pull the Docker image if it isn't already present."""
        probe = subprocess.run(
            ["docker", "image", "inspect", self.image],
            capture_output=True,
            timeout=15,
        )
        if probe.returncode != 0:
            subprocess.run(["docker", "pull", self.image], check=True, timeout=300)

    def _write_hermes_home(self) -> None:
        """Create a minimal Hermes home directory in the temp dir."""
        assert self._temp_dir is not None
        hermes_home = self._temp_dir / ".hermes"
        hermes_home.mkdir(parents=True, exist_ok=True)

        # config.yaml
        if self.config.is_configured:
            (hermes_home / "config.yaml").write_text(
                CONFIG_YAML_TEMPLATE.format(
                    model=self.config.model,
                    provider=self.config.provider,
                )
            )
        else:
            (hermes_home / "config.yaml").write_text("# Minimal config — no provider configured\n")

        # .env
        env_lines = []
        if self.config.api_key:
            provider_upper = self.config.provider.upper()
            env_lines.append(f"{provider_upper}_API_KEY={self.config.api_key}")
        for k, v in self.config.extra_env.items():
            env_lines.append(f"{k}={v}")
        if env_lines:
            (hermes_home / ".env").write_text("\n".join(env_lines) + "\n")

        # Ensure subdirectories exist
        (hermes_home / "plugins").mkdir(exist_ok=True)
        (hermes_home / "skills").mkdir(exist_ok=True)

    def _install_plugin(self) -> None:
        """Copy the plugin into the temp HERMES_HOME so Hermes discovers it."""
        assert self._temp_dir is not None
        dst = self._temp_dir / ".hermes" / "plugins" / self.plugin_name

        if not self.plugin_dir.exists():
            raise FileNotFoundError(f"Plugin dir not found: {self.plugin_dir}")

        if dst.exists():
            shutil.rmtree(dst)

        # If the plugin dir already contains a plugin.yaml, copy the whole
        # tree.  Otherwise, create a minimal plugin.yaml and symlink / copy
        # the source so Hermes can import it.
        if (self.plugin_dir / "plugin.yaml").exists():
            shutil.copytree(self.plugin_dir, dst, symlinks=True)
        else:
            dst.mkdir(parents=True)
            (dst / "plugin.yaml").write_text(PLUGIN_YAML_TEMPLATE.format(name=self.plugin_name))
            # Copy Python package as-is
            for item in self.plugin_dir.iterdir():
                if item.name == "__pycache__":
                    continue
                dest_item = dst / item.name
                if item.is_dir():
                    shutil.copytree(item, dest_item, symlinks=True)
                else:
                    shutil.copy2(item, dest_item)

    def _start_container(self) -> None:
        """Launch the Docker container with the temp HERMES_HOME mounted."""
        assert self._temp_dir is not None

        mount_src = str(self._temp_dir / ".hermes")
        cmd: list[str] = [
            "docker",
            "run",
            "--rm",
            "-d",
            "--name",
            self._container_name,
            "-v",
            f"{mount_src}:/opt/data",
        ]

        # Mount fabricium source if provided (read-only)
        if self.fabricium_src and self.fabricium_src.exists():
            cmd += [
                "-v",
                f"{self.fabricium_src}:/opt/fabricium:ro",
            ]

        # Forward provider env vars
        if self.config.api_key:
            provider_upper = self.config.provider.upper()
            cmd += ["-e", f"{provider_upper}_API_KEY={self.config.api_key}"]
        for k, v in self.config.extra_env.items():
            cmd += ["-e", f"{k}={v}"]

        # PYTHONPATH so the plugin can import fabricium
        pythonpath_parts = []
        if self.fabricium_src:
            # fabricium uses src-layout: src/fabricium/
            pythonpath_parts.append("/opt/fabricium/src")
        if pythonpath_parts:
            cmd += ["-e", f"PYTHONPATH={':'.join(pythonpath_parts)}"]

        cmd += [self.image, "sleep", "infinity"]

        subprocess.run(cmd, check=True, capture_output=True, timeout=60)

    def _install_fabricium(self, *, skip: bool = False) -> None:
        """Install fabricium into the container if a source path was given.

        Uses ``uv pip install`` as root (via ``HERMES_DOCKER_EXEC_AS_ROOT``)
        so it lands in the container's venv.  Does nothing when *skip* is
        ``True`` or no fabricium source was provided.
        """
        if skip or not self.fabricium_src:
            return

        subprocess.run(
            [
                "docker",
                "exec",
                "-e",
                "HERMES_DOCKER_EXEC_AS_ROOT=1",
                self._container_name,
                "uv",
                "pip",
                "install",
                "--python",
                "/opt/hermes/.venv/bin/python3",
                "-e",
                "/opt/fabricium",
            ],
            check=True,
            capture_output=True,
            timeout=120,
        )

    def _enable_plugin(self) -> None:
        """Enable the plugin so Hermes discovers its CLI commands.

        Hermes plugins are opt-in by default.  We call
        ``hermes plugins enable <name>`` to activate this plugin.
        The command is non-interactive when stdin is not a TTY.
        """
        subprocess.run(
            [
                "docker",
                "exec",
                self._container_name,
                "hermes",
                "plugins",
                "enable",
                self.plugin_name,
            ],
            check=True,
            capture_output=True,
            timeout=30,
        )

    def _wait_ready(self, timeout: float = 15.0) -> None:
        """Wait until ``hermes --version`` succeeds inside the container."""
        deadline = time.monotonic() + timeout
        last_error = ""
        while time.monotonic() < deadline:
            proc = subprocess.run(
                ["docker", "exec", self._container_name, "hermes", "--version"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if proc.returncode == 0:
                return
            last_error = proc.stderr.strip() or proc.stdout.strip()
            time.sleep(1.0)
        raise RuntimeError(f"Hermes not ready after {timeout}s: {last_error}")
